# Generated by Django 4.2.6 on 2023-12-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageNews',
            fields=[
                ('idImageNews', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='imageNews/')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '02 Images News',
                'db_table': 'ImageNews',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('idNews', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=255, null=True, verbose_name='New Title')),
                ('titulo', models.CharField(blank=True, db_column='titulo', max_length=255, null=True, verbose_name='Titulo noticia en Español')),
                ('body', models.TextField(db_column='body', verbose_name='New Body')),
                ('cuerpo', models.TextField(db_column='cuerpo', verbose_name='Cuerpo de la noticia en Español')),
                ('coverImage', models.ImageField(upload_to='coverNewsImage/')),
                ('Images', models.ManyToManyField(blank=True, to='news.imagenews')),
            ],
            options={
                'verbose_name_plural': '01 News',
                'db_table': 'News',
                'ordering': ['-date'],
            },
        ),
    ]
