# Generated by Django 4.2.6 on 2023-12-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('idAboutUs', models.BigAutoField(db_column='idAboutUs', primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=255, null=True, verbose_name='Title About Us')),
                ('titulo', models.CharField(blank=True, db_column='titulo', max_length=255, null=True, verbose_name='Titulo en Español')),
                ('body', models.TextField(db_column='body', verbose_name='Body About Us')),
                ('cuerpo', models.TextField(db_column='cuerpo', verbose_name='Cuerpo en Español Acerca de Nosotros')),
            ],
            options={
                'verbose_name_plural': '01 About Us',
                'db_table': 'AboutUs',
                'ordering': ['-date'],
            },
        ),
    ]
