# Generated by Django 4.2.6 on 2023-12-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProjects',
            fields=[
                ('idImageProjects', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='imageProjects/')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '02 Images Projects',
                'db_table': 'ImageProjects',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('idProjects', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('date_project', models.DateField()),
                ('title', models.CharField(blank=True, db_column='title', max_length=255, null=True, verbose_name='Project Title')),
                ('titulo', models.CharField(blank=True, db_column='titulo', max_length=255, null=True, verbose_name='Titulo del Proyecto en Español')),
                ('body', models.TextField(db_column='body', verbose_name='Project Body')),
                ('cuerpo', models.TextField(db_column='cuerpo', verbose_name='Descripcion del Proyecto en Español')),
                ('coverImage', models.ImageField(upload_to='coverProjectsImage/')),
                ('Images', models.ManyToManyField(blank=True, to='project.imageprojects')),
            ],
            options={
                'verbose_name_plural': '01 Projects',
                'db_table': 'Projects',
                'ordering': ['-date'],
            },
        ),
    ]
